name: account_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  get: any
  font_awesome_flutter: any
  sqflite: any
  intl: any
  path_provider: any
  file_picker: any
  
  firebase_core: any

  google_sign_in: any
  googleapis: 
  syncfusion_flutter_pdf: ^22.2.10
  open_file:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  # remove_alpha_ios: true
  image_path: "assets/images/logo1.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo1.png"

  #min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  uses-material-design: true

  assets: 
  - "assets/images/"
   
    
  
  fonts:
  - family: Cairo
    fonts:
      - asset: assets/fonts/Cairo-Regular.ttf
      - asset: assets/fonts/Cairo-Bold.ttf
      - asset: assets/fonts/Cairo-Light.ttf
      - asset: assets/fonts/Cairo-Medium.ttf
